version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: prestamos-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: prestamos2024
      MONGO_INITDB_DATABASE: sistema-prestamos
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - prestamos-network

  backend:
    build: ./backend
    container_name: prestamos-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:prestamos2024@mongodb:27017/sistema-prestamos?authSource=admin
      JWT_SECRET: tu_secreto_super_seguro_cambialo_en_produccion
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - prestamos-network

  frontend:
    build: ./frontend
    container_name: prestamos-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - prestamos-network

volumes:
  mongodb_data:
    driver: local

networks:
  prestamos-network:
    driver: bridge